In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [4]:
!pip install nltk scikit-learn spacy
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 47.5 MB/s eta 0:00:0000:010:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [5]:
import re 

text = "Email ami@gmail.com  phone 123948"

emails = re.findall(f"\w+@\w+.\w+",text)
numbers = re.findall(f"\d+", text)

print(emails)
print(numbers)

['ami@gmail.com']
['123948']


<>:5: SyntaxWarning: invalid escape sequence '\w'
<>:6: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\w'
<>:6: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_58/1653758915.py:5: SyntaxWarning: invalid escape sequence '\w'
  emails = re.findall(f"\w+@\w+.\w+",text)
/tmp/ipykernel_58/1653758915.py:6: SyntaxWarning: invalid escape sequence '\d'
  numbers = re.findall(f"\d+", text)


In [6]:
from nltk.tokenize import word_tokenize

text = "Hello,world! I am learning NLP"
tokens = word_tokenize(text)
print(tokens)

['Hello', ',', 'world', '!', 'I', 'am', 'learning', 'NLP']


In [7]:
from nltk.stem import PorterStemmer, WordNetLemmatizer

ps = PorterStemmer()
lem = WordNetLemmatizer()

print(ps.stem("running"))
print(lem.lemmatize("running", pos="v"))

run
run


In [8]:
#vectorization
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

docs = ["cat sat", "dog ran", "cat dog "]

#one hot {binary}
onehot = CountVectorizer(binary=True)
print(onehot.fit_transform(docs).toarray())

#bag of words

bow = CountVectorizer()
print(bow.fit_transform(docs).toarray())

#N gram = unigram + bigram
ngram =CountVectorizer(ngram_range=(1,2))
print(ngram.fit_transform(docs).toarray())

#TF_IDF

tfidf = TfidfVectorizer()
print(tfidf.fit_transform(docs).toarray())



[[1 0 0 1]
 [0 1 1 0]
 [1 1 0 0]]
[[1 0 0 1]
 [0 1 1 0]
 [1 1 0 0]]
[[1 0 1 0 0 0 1]
 [0 0 0 1 1 1 0]
 [1 1 0 1 0 0 0]]
[[0.60534851 0.         0.         0.79596054]
 [0.         0.60534851 0.79596054 0.        ]
 [0.70710678 0.70710678 0.         0.        ]]


In [9]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop = set(stopwords.words("english"))

text = "the cat is on the mat"

tokens = word_tokenize(text.lower())
clean = [word for word in tokens if word.isalpha() and word not in stop]
print(clean)

['cat', 'mat']


In [13]:
import nltk
from nltk.tokenize import word_tokenize
# nltk.download('popular')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

text = "The cat runs fast"

tokens = word_tokenize(text)
tags = nltk.pos_tag(tokens)

print(tags)

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


[('The', 'DT'), ('cat', 'NN'), ('runs', 'VBZ'), ('fast', 'RB')]


In [15]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Elon musk visited delhi on monday"

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ent.label_)

monday DATE


In [16]:
import spacy 
nlp =spacy.load("en_core_web_sm")
doc = nlp("apple is buysing startup")

for token in doc:
    print(token.text, token.pos_, token.lemma_)

apple PROPN apple
is AUX be
buysing AUX buysing
startup VERB startup


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

texts = [
    "good movie",
    "good film",
    "great movie",
    "great film",
    "bad movie",
    "bad film",
    "terrible movie",
    "terrible film"
]

labels = ["pos", "pos", "pos", "pos", "neg", "neg", "neg", "neg"]

X_train, X_test, y_train, y_test = train_test_split(
    texts,
    labels,
    test_size=0.25,
    random_state=42,
    stratify=labels
)

vec = CountVectorizer()

X_train_vec = vec.fit_transform(X_train)
X_test_vec = vec.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

pred = model.predict(X_test_vec)

print(accuracy_score(y_test, pred))

1.0


In [19]:
word_tokenize(text)
stopwords.words("english")
PorterStemmer().stem("running")
WordNetLemmatizer().lemmatize("running", pos="v")
CountVectorizer()
TfidfVectorizer()
nltk.pos_tag(word_tokenize(text))
spacy.load("en_core_web_sm")
train_test_split(X, y, test_size=0.25)
accuracy_score(y_test, pred)

NameError: name 'X' is not defined